inbo/niche_vlaanderen

niche_vlaanderen/system_tables/floodplains/potential.csv

@cecileherr : can you review - are these labels ok?

Translate potential labels (Closes: #107)

---

docs/invoer.rst

Volgens nieuwe structuur en verschillende toevoegingen en aanpassingen

Aanpassing bodem, GXG en kwel

---

docs/_static/niche_hab_rbb.csv
docs/_static/vegetatietypen.csv
docs/vegetatietype.rst

I need to refer to some tables from the documentation:
- list of Niche vegetation types
- translation table between Niche vegetation types and natura 2000 habitats
@johanvdw : where should we keep those csv files in our structure?

Add csv files (vegetation types) to docs/_static

---

docs/model.rst

docs/model.rst: changed structure

---

docs/kalibratie.rst
docs/principe.rst
docs/vegetatietype.rst

- principe
- kalibratie
- vegetatietype

Different updates to documentation model

---

docs/ct_vegetation_adj7.csv

for advanced tutorial: "advanced_usage" jupyter notebook

Add adjusted vegetation code table

---

docs/installation.rst

- activate niche_vlaanderen => activate niche
- added activate niche when needed to work inside the niche env

installation.rst: minor corrections

---

docs/invoer.rst

invoer: minor correction to seepage

---

appveyor.yml
tests/test_spatial_context.py

Fix appveyor tests

---

.github/workflows/pages.yml
.github/workflows/tests-coverage.yml

Repair automatic building of docs

---

niche_vlaanderen/niche.py

improve log file if detailed files are stored

---

docs/validation.ipynb
niche_vlaanderen/validation.py
tests/test_validation.py

Fix area in validation if not overlapping

---

niche_vlaanderen/validation.py
tests/test_validation.py

Make overwrite call identical to niche
Closes #325

Add docs for validation.write

---

tests/test_flooding.py

Temporary skip failing test for AIG:
see 
https://github.com/inbo/niche_vlaanderen/issues/333

Skip failing test for now (upstream issue)

---

niche_vlaanderen/validation.py
tests/test_validation.py

Aggregate vegetation mappings before validation.
This should fix issue #328

Validation aggregate

---

niche_vlaanderen/validation.py

Improve docstrings overlay

---

niche_vlaanderen/niche.py

Ignore dev/rc versions when reporting new versions

---

docs/getting_started.ipynb
docs/installation.rst

updated 
- installation.rst (textual changes and replace `activate niche` by `conda activate niche`)
- getting_started.ipynb (replace `activate niche` by `conda activate niche`)

Documentation: replace `activate niche` by `conda activate niche`

---

niche_vlaanderen/niche.py

small PR with a fix to improve feedback on plot creation when I was checking for https://github.com/inbo/niche_vlaanderen/issues/308

Improve error message on none-existing array to plot

---

setup.py

Fix of https://github.com/inbo/niche_vlaanderen/issues/356

Add tables explicitly as namespaced subpackages to fix #356

---

docs/invoer.rst

sign for version >= 2 (negative values for groundwater levels under the ground)

Documentation: new sign for gw levels
